# Generated by Django 3.2.10 on 2021-12-08 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page1',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
