# Generated by Django 3.2.10 on 2021-12-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0002_alter_page1_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='amount',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
