# Generated by Django 3.2.10 on 2021-12-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_page1_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='address_details',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='page1',
            name='card_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='page1',
            name='cvv',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='page1',
            name='expiry',
            field=models.CharField(default='01-01-1950', max_length=200),
        ),
        migrations.AddField(
            model_name='page1',
            name='is_card_authentic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page1',
            name='is_order_authentic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page1',
            name='owner_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
