# Generated by Django 3.2.10 on 2021-12-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0004_auto_20211209_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='is_otp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page1',
            name='otp_code_from_user',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
