# Generated by Django 4.0 on 2021-12-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0007_alter_page1_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='is_address_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page1',
            name='is_card_correct',
            field=models.BooleanField(default=True),
        ),
    ]
