# Generated by Django 4.0 on 2021-12-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0008_page1_is_address_correct_page1_is_card_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page1',
            name='is_card_authentic',
        ),
        migrations.AlterField(
            model_name='page1',
            name='is_address_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page1',
            name='is_card_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page1',
            name='is_order_authentic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page1',
            name='is_otp_correct',
            field=models.BooleanField(default=False),
        ),
    ]
