# Generated by Django 4.0 on 2021-12-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0009_remove_page1_is_card_authentic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page1',
            name='is_otp_correct',
            field=models.BooleanField(default=True),
        ),
    ]
