# Generated by Django 3.2.10 on 2021-12-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0010_alter_page1_is_otp_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page1',
            name='address_details',
        ),
        migrations.AddField(
            model_name='page1',
            name='address',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='page1',
            name='apt_suite',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='page1',
            name='city',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='page1',
            name='country',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
