# Generated by Django 3.2.10 on 2021-12-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0011_auto_20211213_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='is_address_details_checked',
            field=models.BooleanField(default=False),
        ),
    ]
