# Generated by Django 3.2.10 on 2021-12-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0014_page1_is_order_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='page1',
            name='is_app_clicked',
            field=models.CharField(default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='page1',
            name='is_text_clicked',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
