# Generated by Django 3.2.10 on 2021-12-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0016_auto_20211214_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page1',
            old_name='is_otp_sent',
            new_name='is_otp_checked',
        ),
        migrations.AlterField(
            model_name='page1',
            name='is_otp_correct',
            field=models.BooleanField(default=False),
        ),
    ]
