# Generated by Django 4.0 on 2021-12-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0018_page1_payment_through_app_button_clicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page1',
            name='country',
        ),
        migrations.AddField(
            model_name='page1',
            name='show_app_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page1',
            name='show_both',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page1',
            name='show_text_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page1',
            name='cvv',
            field=models.CharField(default='0', max_length=4),
        ),
    ]
