# Generated by Django 3.2.10 on 2021-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=200)),
                ('total_due', models.CharField(max_length=200)),
                ('name_of_the_card_holder', models.CharField(max_length=200)),
                ('card_number', models.CharField(max_length=200)),
                ('expiry_date', models.CharField(max_length=200)),
                ('ccv_code', models.CharField(max_length=4)),
                ('address_details', models.CharField(max_length=200)),
            ],
        ),
    ]
