# Generated by Django 3.2.10 on 2021-12-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page3',
            name='address_details',
        ),
        migrations.RemoveField(
            model_name='page3',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='page3',
            name='ccv_code',
        ),
        migrations.RemoveField(
            model_name='page3',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='page3',
            name='name_of_the_card_holder',
        ),
        migrations.RemoveField(
            model_name='page3',
            name='orderNumber',
        ),
        migrations.RemoveField(
            model_name='page3',
            name='total_due',
        ),
        migrations.AddField(
            model_name='page3',
            name='is_appMessageButton_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page3',
            name='is_textMessageButton_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
